### ISSUE TITLE
Missing OSX Breakpoint

### ISSUE THREAD

**Issue by chaffeqa** [Toucaan/--inch#9]
```
MacBook Pro (16-inch, 2021)
Your Screen Resolution:
1728 x 1117

Screen Width: 1728 pixels
Screen Height: 1117 pixels
DPR(Device Pixel Ratio): 2
Color depth: 30 bits per pixel
```

I had to add to the `--inch.css`:

```css
:root {
  --inch: 96px;
}

@media (resolution: 192dpi) and (-webkit-device-pixel-ratio: 2) {
  :root {
    --inch: 130px;
  }
}
```
